# Learn more about building a configuration: https://promptfoo.dev/docs/configuration/guide
description:  "Ginatayomi evaluation"

prompts:
  - prompts.txt

providers:
  - "openai:gpt-3.5-turbo"
  - "openai:gpt-4o-mini"
  - "openai:gpt-4o"
  - "anthropic:messages:claude-3-haiku-20240307"
  - "anthropic:messages:claude-3-5-sonnet-20240620"
  - "anthropic:messages:claude-3-opus-20240229"
  - "vertex:gemini-1.5-flash-001"
  - "vertex:gemini-1.5-pro"

tests: tests/ginatayomi_test.yaml

outputPath: outputs/result_ginatayomi_test.csv